name: FTP Deploy

on:
  push:
    branches:
      - main          # si tu rama principal se llama distinto, cámbiala aquí
  workflow_dispatch:  # para poder lanzarlo manualmente desde Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkoutrepo
      - uses: actions/checkout@v4

      # Si necesitas compilar (React, Vite, etc.), aquí irían los comandos de build.
      # Por ejemplo:
      # - name: Build project
      #   run: |
      #     npm install
      #     npm run build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./dist    # CAMBIA 'dist' por la carpeta que quie
